### ISSUE TITLE
Recurso para estudo de flask

### ISSUE THREAD

**Issue by baptvit** [Leothi/flask-example#1]
Eai irmão, tudo na paz ?

Vi que vc esta estudando Flask.
Tem esse conteúdo fenomenal que já vai te salvar meses de dor de cabeça o segredo do flask é a definição da arquitetura
https://www.youtube.com/watch?v=-qWySnuoaTM&list=WL&index=47&ab_channel=CodeShow

**Comment by Leothi** [comment]
e aí mano!
eu parei de usar flask depois que o restful e plus foram descontinuados. to usando o FastAPI, que é muito top.
esse repo foi mais pra estudos e pra ajudar uns amigos
